### ISSUE TITLE
Fix build error on Xenial Kinetic with enabled tests

### ISSUE THREAD

**Issue by steup** [robocup-at-work/atwork-commander#22]
On Travis the build failes if tests are enabled on Xenial Kinetic because of errors in boost program_options.

**Comment by steup** [comment]
Currently disabled the test on travis for Xenial Kinetic. If someone needs support for Xenial Kinetic please respond to this issue.

Done in 3cc3de805d6499d79b6dd40a2a65bba324ad23e7

**Comment by sthoduka** [comment]
The build succeeds if the required boost version is downgraded to 1.58 [here](https://github.com/robocup-at-work/atwork-commander/blob/master/atwork_commander_core/CMakeLists.txt#L14) (which I guess is the default in Xenial). I don't know if this affects anything else though.

**Comment by steup** [comment]
Tested and solved the problem. Thanks a lot for the support!

Fixed through d1d334847ce0aeb521952d54d9a5ba54fa2f6d76
