### ISSUE TITLE
Missing call for  roslaunch atwork_commander generate.launch task:=<task to generate>

### ISSUE THREAD

**Issue by florianspy** [robocup-at-work/atwork-commander#25]
Hello,
Can a example call for roslaunch atwork_commander generate.launch task:=<task to generate> be provided, e.g. how would <task to generate> be replaced, i tried it with BMT but i always get the following output in the terminal running the command:
```
[ INFO] [1589967636.031491260]: [REFBOX-CONTROL] Current refbox state: 
	state: 0
end: 0.000000000
task: 
  execute_on[]
  arena_start_state[]
  arena_target_state[]
  prep_time: 0.000000000
  exec_time: 0.000000000
robots[]
```

**Comment by steup** [comment]
Have a look in the config directory of atwork_commander_gen. There you find the configurations of the tasks. The task name needs to match the provided task name. However, BMT should work. Will investigate further.

**Comment by florianspy** [comment]
Here is the debug output:
```
[DEBUG] [1589977832.824882983, 1579261379.125930461]: [REFBOX-CONTROL] Command parsed successfull: Executing "generate task" with arguments [BMT ]
[ INFO] [1589977833.685579647, 1579261379.819456331]: [REFBOX-CONTROL] Current refbox state: 
	state: 0
end: 0.000000000
task: 
  execute_on[]
  arena_start_state[]
  arena_target_state[]
  prep_time: 0.000000000
  exec_time: 0.000000000
robots[]
```

**Comment by steup** [comment]
Bug found, which probably caused the issue. Please check current version and comment.

see ed62659493eb07c8d5f6003665babd4525c447b0

**Comment by florianspy** [comment]
can confirm the bug is now solved.
