### ISSUE TITLE
Problem when starting roslaunch atwork_commander example_robot.launch

### ISSUE THREAD

**Issue by florianspy** [robocup-at-work/atwork-commander#26]
Hello when launching roslaunch atwork_commander example_robot.launch after i started roslaunch atwork_commander atwork_commander.launch  i always get the following output
```
[WARN] [1589967870.146949]: Error while start RPC-XML server on port 11611: [Errno 98] Address already in use
Try again..
```

**Comment by steup** [comment]
This is a non-critical error, because you startet the **Refbox** and the example robot on the same machine. The automatically enabled **ROS Multi-Master** does not work in this case. If you want to get rid of the error message start the _example_robot.launch_ with _multimaster:=false_.
