### ISSUE TITLE
refbox noetic compatibility

### ISSUE THREAD

**Issue by oliverup** [robocup-at-work/atwork-commander#32]
Hi, we just tried to run the atwork_commander in ros noetic and it seems like the naming convention for the multimaster_fkie package changes for noetic. 
 ["The FKIE multimaster packages used to have an _fkie suffix. In conformance with REP-144, all packages have been renamed with an fkie_prefix"](https://github.com/fkie/multimaster_fkie/tree/noetic-devel)
Thus the fkie nodes cannot be found and their topics would have different names. 
I would like to know if anybody has tried to run the refbox in ros noetic or if there are any plans for future implementation.
Greetings Oliver from Team luhbots

**Comment by steup** [comment]
I also had this issue, because I am using melodic with python3 and the multimaster package is not python3 compatible unless the noetic branch is used. I have a fix already in the local repository and will upload a specific noetic-devel branch on the next update.

**Comment by oliverup** [comment]
Okay, that would be perfect. Thank you!

**Comment by steup** [comment]
Not yet uploaded, so reopening to not forget :-)

**Comment by steup** [comment]
Solved by uploading new noetic branch
