### ISSUE TITLE
Error in generate task

### ISSUE THREAD

**Issue by aliakbarhamzeh1378** [robocup-at-work/atwork-commander#8]
hi, 
when I run :
`   roslaunch atwork_commander generate.launch task:=PPT`
it response 
`terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
`

**Comment by steup** [comment]
The error is generated within roscpp during shutdown of the node. The generation is still working correctly.

-  No remedy possible.
- Will add additional output to clearify correct behaviour of application

**Comment by steup** [comment]
Remedy implemented in a30138
