### ISSUE TITLE
Alternative Object-centic ROS-native Task Description

### ISSUE THREAD

**Issue by steup** [robocup-at-work/atwork-commander#9]
- Current ROS-native Task description is workstation-centric
- Provide additional Task description, which is object-centric to ease migration from old task description

**Comment by marcomasa** [comment]
Is there an update for this yet?

**Comment by steup** [comment]
still working on it

**Comment by steup** [comment]
Done through 7b6e2ac011f122cf8c7d58e565c454676e3ecd47
